// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follows.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH insert_feed_follows AS (
    INSERT INTO feed_follows (id, user_id, feed_id, created_at, updated_at)
    VALUES ($1, $2, $3, $4, $5)

    RETURNING id, created_at, updated_at, user_id, feed_id
)

SELECT     
    insert_feed_follows.id, insert_feed_follows.created_at, insert_feed_follows.updated_at, insert_feed_follows.user_id, insert_feed_follows.feed_id,
    feeds.name AS feed_name,
    users.name AS user_name
FROM insert_feed_follows
JOIN users ON users.id = insert_feed_follows.user_id
JOIN feeds ON feeds.id = insert_feed_follows.feed_id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FeedID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CreateFeedFollowRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	FeedName  sql.NullString
	UserName  string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.UserID,
		arg.FeedID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
		&i.FeedName,
		&i.UserName,
	)
	return i, err
}

const getFeedFollowersForUser = `-- name: getFeedFollowersForUser :many


SELECT 
    feed_follows.id, feed_follows.created_at, feed_follows.updated_at, feed_follows.user_id, feed_follows.feed_id,
    users.name,
    feeds.name
FROM feed_follows
JOIN users ON users.id = feeds_follow.user_id
JOIN feeds ON feeds.id = feeds_follows.feed_id
WHERE feed_follows.user_id = $1
`

type getFeedFollowersForUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	Name      string
	Name_2    sql.NullString
}

func (q *Queries) getFeedFollowersForUser(ctx context.Context, userID uuid.UUID) ([]getFeedFollowersForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowersForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []getFeedFollowersForUserRow
	for rows.Next() {
		var i getFeedFollowersForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
			&i.Name,
			&i.Name_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
